### ISSUE TITLE
graphics bug

### ISSUE THREAD

**Issue by saildrag** [Maxlego08/Minecraft-Inventory-Builder#4]
When we have files at the root and a folder containing a file, the name displayed in the folder is the same as the root file.
But when you click it displays the correct inventory so just a graphical bug

**Comment by Maxlego08** [comment]
Can you provide screenshot plz ?

**Comment by saildrag** [comment]
![Capture d'écran 2024-02-25 114028](https://github.com/Maxlego08/Minecraft-Inventory-Builder/assets/89639054/63afbcdc-5ca6-4ea9-8f9b-7f58bf84213a)
![Capture d'écran 2024-02-25 113955](https://github.com/Maxlego08/Minecraft-Inventory-Builder/assets/89639054/ec675cbd-dfdb-4425-9928-fb21185a7949)

**Comment by Maxlego08** [comment]
Its fix for the next version

**Comment by saildrag** [comment]
fixed
