### ISSUE TITLE
Zmenu spawn egg - Doesn't work properly

### ISSUE THREAD

**Issue by bobbyrossy12** [Maxlego08/Minecraft-Inventory-Builder#7]

**Comment by bobbyrossy12** [comment]
When adding in spawn eggs into a GUI, when added into game it becomes stone, likely because it adds in for example "GHAST_EGG" instead of "GHAST_SPAWN_EGG" into the configuration

**Comment by bobbyrossy12** [comment]
The same thing happens with an ender chest

**Comment by Maxlego08** [comment]
Thx, its fixed !
